### ISSUE TITLE
Error Message when trying to add device 

### ISSUE THREAD

**Issue by k2dp2k** [SWW13/homeassistant-victron-ir-ble#4]
Hi i get the following error message: 

Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

in the logs:

Logger: homeassistant.config_entries
Source: config_entries.py:2077
First occurred: 08:49:10 (4 occurrences)
Last logged: 09:08:06

Error occurred loading flow for integration victron_ir: cannot import name 'BatterySenseData' from 'victron_ble.devices' (/usr/local/lib/python3.11/site-packages/victron_ble/devices/__init__.py)

Whats wrong here??

**Comment by k2dp2k** [comment]
update: after reinstalling the package the errr above is gone... but when i try to add an device using integrations, i only been ask if i want to configure, after that only this window is displayed, but no device is set up....
<img width="437" alt="Bildschirmfoto 2023-12-06 um 09 26 46" src="https://github.com/SWW13/homeassistant-victron-ir-ble/assets/45642270/247639b9-14ef-4f27-a62f-64d85256d793">

**Comment by SWW13** [comment]
Are you using the "configure discovered device" or the "+ add integration" button?

First option is currently broken. If you use the later can you check if Bluetooth is working correctly and see if it discovers your device with a "configure discovered device" message?

**Comment by k2dp2k** [comment]
I'm using the +button... Bluetooth is working, I have a temperature an door sensor connected via ble

**Comment by SWW13** [comment]
Okay, does HA auto discovery your victron device?

If not, can you check if the "Instant Readout" is enabled? Also which device type do you want to add?

**Comment by k2dp2k** [comment]
Yes the device is discovered, the shunt is also working using the victron ble addon... now i get the following error... Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

**Comment by SWW13** [comment]
Do have successfully added a shunt device and want to add another device or do you have issues with adding the shunt device?

Can you name the model of the devices you have added / want to add?
