### ISSUE TITLE
Error after update to Home Assistant 2024.1

### ISSUE THREAD

**Issue by snipah** [SWW13/homeassistant-victron-ir-ble#6]
After updating to Home Assistant 2024.1 the implementation does not load anymore.

Error occurred loading flow for integration victron_ir: cannot import name 'BluetoothScanningMode' from 'homeassistant.components.bluetooth.models' (/usr/src/homeassistant/homeassistant/components/bluetooth/models.py)
01:24:47 – (FEHLER) config_entries.py - Die Nachricht ist zum ersten Mal am 01:24:47 aufgetreten und erscheint 2 mal
Setup failed for custom integration 'victron_ir': Unable to import component: cannot import name 'BluetoothScanningMode' from 'homeassistant.components.bluetooth.models' (/usr/src/homeassistant/homeassistant/components/bluetooth/models.py)
01:24:47 – (FEHLER) setup.py

**Comment by SWW13** [comment]
Looks like a lot of bluetooth refactoring was done in 2024.1 without any documentation of the changes:
https://www.home-assistant.io/changelogs/core-2024.1

Going to be fun to reverse engineer the breaking changes.

**Comment by SWW13** [comment]
That was easier than expected, fixed in c5a29fdc7a9286030fbc58cd8eb3616e71093220.
